# Generated by Django 5.1.3 on 2025-01-11 16:56

import app.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PongGameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamemode', models.TextField()),
                ('players', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('scores', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('timeStarted', models.IntegerField()),
                ('timeEnded', models.IntegerField()),
                ('tid', models.CharField(max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('playerCount', models.IntegerField()),
                ('openType', models.TextField()),
                ('password', models.TextField(null=True)),
                ('game', models.TextField()),
                ('fillWithAI', models.BooleanField()),
                ('gameSettings', models.JSONField()),
                ('tid', models.CharField(max_length=8)),
                ('players', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('steps', models.JSONField(default=dict)),
                ('state', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='accessToken',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='blockedUsers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='player',
            name='external',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='friends',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='player',
            name='nickname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='skins',
            field=models.JSONField(default=app.models.default_skins),
        ),
    ]
