# Generated by Django 5.1.3 on 2025-01-22 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_ponggameresult_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ponggameresult',
            name='players',
        ),
        migrations.RemoveField(
            model_name='ponggameresult',
            name='scores',
        ),
        migrations.AddField(
            model_name='ponggameresult',
            name='player1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pgames_as_player1', to='app.player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ponggameresult',
            name='player2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pgames_as_player2', to='app.player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ponggameresult',
            name='score1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ponggameresult',
            name='score2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='player',
            name='friends',
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='app.player')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='app.player')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_as_player1', to='app.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_as_player2', to='app.player')),
                ('messages', models.ManyToManyField(related_name='chats', to='app.message')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='friends',
            field=models.ManyToManyField(related_name='friend_set', to='app.player'),
        ),
    ]
