# Generated by Django 5.1.3 on 2025-01-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_ponggameresult_player1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='channelList',
            field=models.JSONField(default=list),
        ),
    ]
