# Generated by Django 5.1.3 on 2025-01-28 17:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_ponggameresult_player1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='channelList',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
        migrations.AddField(
            model_name='player',
            name='discussingWith',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
    ]
