# Generated by Django 5.1.3 on 2025-01-29 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_chat_created_at_chat_channel_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='channel_url',
            new_name='channel_name',
        ),
    ]
