# Generated by Django 5.1.3 on 2025-01-28 12:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_player_channellist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='channelList',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
    ]
