# Generated by Django 5.1.3 on 2025-01-29 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_player_channellist_player_discussingwith'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='created_at',
        ),
        migrations.AddField(
            model_name='chat',
            name='channel_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
