import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap/dist/js/bootstrap.bundle.min.js";
import Home from "./views/Home";
import Profile from "./views/Profile";
import Settings from "./views/Settings";
import NotFound from "./views/NotFound";

const router = async () => {
    // Define routes and their associated views.
    // This allows us to dynamically render HTML content based on the current view.
    const routes = [
        { path: "/404", view: NotFound },
        { path: "/", view: Home },
        { path: "/profile", view: Profile },
        { path: "/settings", view: Settings },
    ];

    // Create an array of potential matches by mapping routes to their match status.
    // This helps us determine if the current path exists in our routes array.
    const potentialMatches = routes.map((route) => {
        return {
            route: route,
            isMatch: location.pathname === route.path,
        };
    });

    // TODO: Implement a 404 page for unmatched routes.
    let match = potentialMatches.find((potentialMatch) => potentialMatch.isMatch);
    if (!match) {
        match = {
            route: routes[0],
            isMatch: true,
        };
    }

    // Instantiate the view associated with the matched route.
    const view = new match.route.view();

    // Render the HTML content generated by the view class into the app placeholder.
    document.querySelector("#app").innerHTML = await view.getHtml();

    // Handle browser navigation events (back/forward buttons).
    window.onpopstate = () => {
        router();
    };
};

// Update the browser's history with the new URL and render the corresponding view.
const navigateTo = (url) => {
    history.pushState(null, null, url);
    router();
};

// If the clicked element contains a data-link attribute, prevent the default page reload,
// update the browser's history, and render the new HTML content.
document.addEventListener("DOMContentLoaded", () => {
    document.body.addEventListener("click", (event) => {
        if (event.target.matches("[data-link]")) {
            event.preventDefault();
            navigateTo(event.target.href);
        }
    });
    router();
});
