BAD_PASSWORD = "Bad password"
ALREADY_IN_GAME = "Already in game"
USERNAME_ALREADY_TAKEN = "Username is already taken"
INVALID_USERNAME = "Invalid username"
INVALID_NICKNAME = "Invalid nickname"
INVALID_TOURNAMENT_NAME = "Invalid tournament name"
INVALID_TOKEN = 'Invalid token'
MISMATCH_CREDENTIALS = "Mismatch username and password"
NOT_LOGGED_IN = "User is not logged in"
NOT_AUTHENTICATED = "User is not authenticated"
INTERNAL_ERROR = "Internal error"
INVALID_USER_ID = "Invalid user identifier"
INVALID_IMAGE_FORMAT = "Invalid image format"
INVALID_REQUEST = "Invalid request"
TOURNAMENT_DOESNT_EXISTS = "Tournament does not exists"
IMAGE_TOO_BIG = "Profile picture exceed max size"
NICKNAME_ALREADY_USED = "Nickname is already used"
OTP_INVALID = "One time code is invalid"
EMAIL_ALREADY_USED = "Email is already used by another account"
USER_NOT_FOUND = "User not found"
NICKNAME_TOO_LONG = "The nickname is too long. Please choose another one."

INVALID_SKIN = "Invalid skin"
FRIEND_NOT_FOUND = "Friend not found."
CHAT_NOT_FOUND = "Chat not found."
RECEIVER_NOT_FOUND = "Receiver not found."
FRIEND_ALREADY_IN_LIST = "Friend already in list"
FRIEND_BLOCKED = "You are blocked by this user"
INVALID_FRIEND_ID = "Invalid friend ID"

INVALID_BLOCKED_USER_ID = "Invalid blocked user ID"
BLOCKED_USER_NOT_FOUND = "Blocked user not found."
BLOCKED_USER_ALREADY_IN_LIST = "Blocked user already in list"

API_UNAVAILABLE = "42 API is currently unavailable"
