BAD_PASSWORD = "Bad password"
ALREADY_IN_GAME = "Already in game"
USERNAME_ALREADY_TAKEN = "Username is already taken"
MISMATCH_CREDENTIALS = "Mismatch username and password"
NOT_LOGGED_IN = "User is not logged in"
NOT_AUTHENTICATED = "User is not authenticated"
INTERNAL_ERROR = "Internal error"
INVALID_USER_ID = "Invalid user identifier"
INVALID_IMAGE_FORMAT = "Invalid image format"
INVALID_REQUEST = "Invalid request"
TOURNAMENT_DOESNT_EXISTS = "Tournament does not exists"
IMAGE_TOO_BIG = "Profile picture exceed max size"

INVALID_SKIN = "Invalid skin"
FRIEND_NOT_FOUND = "Friend not found."
CHAT_NOT_FOUND = "Chat not found."
RECEIVER_NOT_FOUND = "Receiver not found."

