# Generated by Django 5.1.3 on 2024-12-11 13:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PongGameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamemode', models.TextField()),
                ('players', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), size=None)),
                ('scores', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('timeStarted', models.IntegerField()),
                ('timeEnded', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PongOngoingGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(max_length=8)),
                ('gamemode', models.TextField()),
                ('players', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), size=None)),
                ('scores', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('timeStarted', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='gid',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='nickname',
            field=models.CharField(max_length=20),
        ),
    ]
