# Generated by Django 5.1.3 on 2025-01-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ponggameresult_tournament_player_accesstoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponggameresult',
            name='stats',
            field=models.JSONField(default=dict),
        ),
    ]
