# Generated by Django 5.1.3 on 2024-12-17 10:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ponggameresult_pongongoinggame_player_gid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='gid',
        ),
        migrations.AddField(
            model_name='player',
            name='blockedUsers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='player',
            name='friends',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='ponggameresult',
            name='players',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
        migrations.AlterField(
            model_name='pongongoinggame',
            name='players',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
    ]
