# Generated by Django 5.1.3 on 2024-12-18 11:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_player_gid_player_blockedusers_player_friends_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('playerCount', models.IntegerField()),
                ('openType', models.TextField()),
                ('password', models.TextField(null=True)),
                ('game', models.TextField()),
                ('fillWithAI', models.BooleanField()),
                ('gameSettings', models.JSONField()),
                ('tid', models.CharField(max_length=8)),
                ('players', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('steps', models.JSONField(default=dict)),
                ('state', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='ponggameresult',
            name='tid',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='pongongoinggame',
            name='tid',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
