# Generated by Django 5.1.3 on 2025-01-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_ponggameresult_players_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponggameresult',
            name='player1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ponggameresult',
            name='player2',
            field=models.IntegerField(),
        ),
    ]
