# Generated by Django 5.1.3 on 2024-12-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tournament_ponggameresult_tid_pongongoinggame_tid'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='accessToken',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='external',
            field=models.BooleanField(default=False),
        ),
    ]
