# Generated by Django 5.1.3 on 2025-01-30 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_chat_channel_name_player_channellist_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='chat',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='player2',
        ),
    ]
