# Generated by Django 5.1.3 on 2025-01-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_chat_unique_together_remove_chat_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
