# Generated by Django 5.1.3 on 2025-02-04 01:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_player_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='discussingWith',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
