# Generated by Django 5.1.3 on 2025-02-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_player_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='blockedUsers',
        ),
        migrations.AddField(
            model_name='player',
            name='blockedUsers',
            field=models.ManyToManyField(to='app.player'),
        ),
    ]
